<?php

$this->mainMenu()->setActiveItemId('help');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'download'=>$this->url('download'),
]);


$this->headTitle('Typeahead');
// Add a JavaScript file
$this->headScript()->appendFile('/js/typeahead.bundle.js', 'text/javascript');
?>

<h1>Typeahead</h1>
<p>Type a continent name (e.g. Africa) in the text field below:</p>
<input type="text" class="typeahead" title="Type here"/>

<script type="text/javascript">
    $(document).ready(function() {

        $('input.typeahead').typeahead({
            name: 'continents',
            local: [
                'Africa',
                'Antarctica',
                'Asia',
                'Europe',
                'South America',
                'North America'
            ]
        });
    });
</script>

<h1>Help</h1>

<p>
    See the help <a href="<?= $this->url('static',
        ['page'=>'/chapter1/intro']); ?>">introduction</a> here.
</p>