<style type="text/css">
    form ul {
        list-style-type: none;
        padding: 0px;
        margin: 0px 5px;
    }

    form ul li {
        color: red;
    }

</style>

<?php

$form = $this->form;
$form->prepare();

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
]);

$form->get('subject')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Type subject here'
]);

$form->get('body')->setAttributes([
    'class' => 'form-control',
    'rows' => 6,
    'placeholder' => 'Type message text here'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

?>
<h1>Contact Us</h1>

<p>
    Please fill out the following form to contact us.
    We appreciate your feedback.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('subject')); ?>
            <?= $this->formElement($form->get('subject')); ?>
            <?= $this->formElementErrors($form->get('subject')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('body')); ?>
            <?= $this->formElement($form->get('body')); ?>
            <?= $this->formElementErrors($form->get('body')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<!--<form name="contact-form" action="/contactus" method="post">-->
<!---->
<!--    <div class="form-group">-->
<!--        <label for="email">Your E-mail</label>-->
<!--        <input name="email" type="text" class="form-control"-->
<!--               placeholder="name@example.com">-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <label for="subject">Subject</label>-->
<!--        <input name="subject" type="text" class="form-control"-->
<!--               placeholder="Type subject here">-->
<!--    </div>-->
<!---->
<!--    <div class="form-group">-->
<!--        <label for="body">Message Body</label>-->
<!--    <textarea name="body" class="form-control" rows="6"-->
<!--              placeholder="Type message text here"></textarea>-->
<!--    </div>-->
<!---->
<!--    <input name="submit" type="submit"-->
<!--           class="btn btn-primary" value="Submit">-->
<!--</form>-->